version: "3"

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./migrations/create_refresh_tokens.up.sql:/docker-entrypoint-initdb.d/create_refresh_tokens.sql
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=mydb
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db-data:
